import { useState } from 'react';
import { ShoppingCart, Copy, ExternalLink, Check, AlertCircle } from 'lucide-react';
import { DiagnoseResponse, BasketItem, BasketItemPriority } from '../types';
import { RETAILERS, buildAffiliateUrl, RetailerKey } from '../config/affiliates';

const RETAILER_KEYS: RetailerKey[] = ['bq', 'screwfix', 'toolstation', 'wickes'];

const PRIORITY_LABELS: Record<BasketItemPriority, string> = {
  essential: 'Essential',
  recommended: 'Recommended',
  optional: 'Optional',
};

function extractBasketItems(result: DiagnoseResponse): BasketItem[] {
  if (result.mode === 'project_planning') {
    return result.shoppingList.map((item, i) => ({
      id: `shop-${i}`,
      name: item.item,
      quantity: item.quantity,
      estimatedCost: item.estimatedCost,
      searchQuery: item.searchQuery,
      category: item.category,
      priority: item.priority,
    }));
  }
  return result.productSuggestions.map((p, i) => ({
    id: `prod-${i}`,
    name: p.name,
    quantity: '1',
    estimatedCost: p.estimatedPrice,
    searchQuery: p.searchQuery,
    category: p.category,
    priority: p.priority === 'useful' ? 'recommended' : (p.priority as BasketItemPriority),
  }));
}

function formatCopyList(items: BasketItem[], retailerName: string): string {
  const groups: BasketItemPriority[] = ['essential', 'recommended', 'optional'];
  const lines: string[] = [
    'Shopping List — DI-MY',
    '──────────────────────',
    '',
  ];

  for (const priority of groups) {
    const group = items.filter(i => i.priority === priority);
    if (group.length === 0) continue;
    lines.push(`${PRIORITY_LABELS[priority].toUpperCase()} (${group.length} item${group.length !== 1 ? 's' : ''})`);
    for (const item of group) {
      const cost = item.estimatedCost ? `  ~${item.estimatedCost}` : '';
      const qty = item.quantity ? `  ${item.quantity}` : '';
      lines.push(`• ${item.name}${qty}${cost}`);
    }
    lines.push('');
  }

  lines.push('──────────────────────');
  lines.push(`Retailer: ${retailerName}`);
  lines.push('Prices are estimates. Check size, stock and compatibility before buying.');
  lines.push('Generated by DI-MY');

  return lines.join('\n');
}

interface Props {
  result: DiagnoseResponse;
}

export default function BasketPanel({ result }: Props) {
  const [retailer, setRetailer] = useState<RetailerKey>('bq');
  const [copied, setCopied] = useState(false);
  const [openAllWarning, setOpenAllWarning] = useState(false);

  const items = extractBasketItems(result);
  if (items.length === 0) return null;

  const groups: BasketItemPriority[] = ['essential', 'recommended', 'optional'];
  const retailerConfig = RETAILERS[retailer];

  function handleCopy() {
    const text = formatCopyList(items, retailerConfig.name);
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  function handleOpenAll() {
    const essential = items.filter(i => i.priority === 'essential');
    const toOpen = essential.length > 0 ? essential : items;
    if (toOpen.length > 5) setOpenAllWarning(true);
    toOpen.forEach(item => {
      window.open(buildAffiliateUrl(retailer, item.searchQuery), '_blank', 'noopener,noreferrer');
    });
  }

  return (
    <div className="card basket-panel">
      <div className="card-header">
        <ShoppingCart size={20} color="#FF6B35" />
        <span className="card-title">Build my basket</span>
      </div>

      <p className="basket-intro">
        Choose your preferred retailer — links open a search for each item.
      </p>

      {/* Retailer selector */}
      <div className="basket-retailer-tabs">
        {RETAILER_KEYS.map(key => {
          const r = RETAILERS[key];
          return (
            <button
              key={key}
              className={`basket-retailer-tab${retailer === key ? ' active' : ''}`}
              style={retailer === key ? { borderColor: r.color, color: r.color, background: `${r.color}12` } : undefined}
              onClick={() => setRetailer(key)}
            >
              {r.name}
            </button>
          );
        })}
      </div>

      {/* Items by priority */}
      <div className="basket-items">
        {groups.map(priority => {
          const group = items.filter(i => i.priority === priority);
          if (group.length === 0) return null;
          return (
            <div key={priority} className="basket-priority-group">
              <div className={`basket-priority-label basket-priority-${priority}`}>
                {PRIORITY_LABELS[priority]}
              </div>
              {group.map(item => (
                <a
                  key={item.id}
                  href={buildAffiliateUrl(retailer, item.searchQuery)}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="basket-item"
                >
                  <div className="basket-item-main">
                    <span className="basket-item-name">{item.name}</span>
                    {item.quantity && (
                      <span className="basket-item-qty">{item.quantity}</span>
                    )}
                  </div>
                  <div className="basket-item-right">
                    {item.estimatedCost && (
                      <span className="basket-item-cost">{item.estimatedCost}</span>
                    )}
                    <ExternalLink size={13} className="basket-item-icon" />
                  </div>
                </a>
              ))}
            </div>
          );
        })}
      </div>

      {/* Action buttons */}
      <div className="basket-actions">
        <button className="basket-action-btn" onClick={handleCopy}>
          {copied ? <Check size={15} /> : <Copy size={15} />}
          {copied ? 'Copied!' : 'Copy shopping list'}
        </button>
        <button className="basket-action-btn basket-open-btn" onClick={handleOpenAll}>
          <ExternalLink size={15} />
          Open all searches
        </button>
      </div>

      {openAllWarning && (
        <div className="basket-open-warning">
          <AlertCircle size={13} style={{ flexShrink: 0, marginTop: 1 }} />
          <span>
            Your browser may block multiple tabs. If nothing opens, allow pop-ups for this site and try again.
          </span>
        </div>
      )}

      {/* Disclaimer */}
      <p className="basket-disclaimer">
        Prices are estimates. Check size, stock and compatibility before buying.
        Links open {retailerConfig.name} search results — always verify the product matches your requirements.
      </p>
    </div>
  );
}
